name: Release_Pipeline_Windows
'on':
  push:
    branches:
      - master
  schedule:
      - cron: '40 16 * * *' 
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute Behave tests
        run: |
          cd features
          behave OrgangeHRMLogin.feature
      - name: Execute Behave tests
        run: |
          pwd 
      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: JunitReports\TESTS-*.xml
      
